{% set name = "ConfigSpace" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: d23fa9006a768266af539946d61c3cc5b59662286185333baf57fc0313850ab1

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyparsing
    - scipy
    - typing_extensions
    - more-itertools

test:
  imports:
    - ConfigSpace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfeurer
    - BastianZim
