{% set name = "ConfigSpace" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 2fc1c4477f7839d38b53d8813c2581967df57ccd7d8b4b506e879a8835cb964c

build:
  number: 0
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - numpy
    - python
    - pyparsing
    - scipy
    - typing_extensions
    - more-itertools

test:
  imports:
    - ConfigSpace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfeurer
    - BastianZim
