{% set name = "ConfigSpace" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ConfigSpace-{{ version }}.tar.gz
  sha256: c8b61fe119829c29c47fc8719bb5f5740ae3034c793040f7bff67dbc9eb9c754

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - cython
    - pyparsing
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ConfigSpace
    - ConfigSpace.nx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
